# permissions for end users to edit ec2instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec2instance-editor-role
rules:
- apiGroups:
  - lucas.lucas.dev
  resources:
  - ec2instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lucas.lucas.dev
  resources:
  - ec2instances/status
  verbs:
  - get
